import { Phase, ClientCard } from './types';

export const PHASES: Phase[] = [
  {
    id: 'new-inquiry',
    title: 'Neue Anfrage',
    description: 'First contact received, not yet qualified',
  },
  {
    id: 'consultation-scheduled',
    title: 'Erstgespräch geplant',
    description: 'Meeting booked, awaiting first call',
  },
  {
    id: 'documents-requested',
    title: 'Unterlagen angefordert',
    description: 'Waiting for the client to submit required documents',
  },
  {
    id: 'documents-received',
    title: 'Unterlagen erhalten',
    description: 'All docs in, internal review in progress',
  },
  {
    id: 'engagement-letter-sent',
    title: 'Mandatsvertrag versendet',
    description: 'Contract sent out, awaiting signature',
  },
  {
    id: 'signed-active',
    title: 'Unterschrieben & Aktiv',
    description: 'Client fully onboarded, handed over to the team',
  },
  {
    id: 'on-hold',
    title: 'Pausiert',
    description: 'Onboarding stalled for any reason',
  },
];

export const TEAM_MEMBERS = [
  'Sarah Müller',
  'Thomas Weber',
  'Anna Schmidt',
  'Markus Fischer',
  'Laura Hoffmann',
];

export const SAMPLE_CARDS: ClientCard[] = [
  {
    id: '1',
    clientName: 'Max Mustermann',
    email: 'max@mustermann.de',
    phone: '+49 170 1234567',
    mandateType: 'Einkommensteuer',
    assignedTo: 'Sarah Müller',
    dateAdded: '2026-06-15',
    status: 'normal',
    notes: 'Anfrage über Website-Formular. Möchte Steuererklärung 2025 abgeben.',
    phaseId: 'new-inquiry',
  },
  {
    id: '2',
    clientName: 'TechStart GmbH',
    email: 'info@techstart.de',
    phone: '+49 30 9876543',
    mandateType: 'GmbH',
    assignedTo: 'Thomas Weber',
    dateAdded: '2026-06-12',
    status: 'vip',
    notes: 'Neugründung, braucht laufende Buchhaltung + Jahresabschluss. Termin Mittwoch 14:00.',
    phaseId: 'consultation-scheduled',
  },
  {
    id: '3',
    clientName: 'Lisa Kreativ',
    email: 'lisa@kreativstudio.com',
    phone: '+49 151 5551234',
    mandateType: 'Freelancer',
    assignedTo: 'Anna Schmidt',
    dateAdded: '2026-06-10',
    status: 'waiting',
    notes: 'Fehlende BWA und Kontoauszüge Q1. Erinnerung gesendet am 18.06.',
    phaseId: 'documents-requested',
  },
  {
    id: '4',
    clientName: 'Familie Bergmann',
    email: 'bergmann.familie@gmail.com',
    phone: '+49 160 7778899',
    mandateType: 'Erbschaftsteuer',
    assignedTo: 'Markus Fischer',
    dateAdded: '2026-06-08',
    status: 'urgent',
    notes: 'Erbfall mit Immobilie. Frist läuft in 4 Wochen ab. Alle Unterlagen vollständig.',
    phaseId: 'documents-received',
  },
  {
    id: '5',
    clientName: 'Digital Nomad UG',
    email: 'hello@digitalnomad.ug',
    phone: '+49 176 3334455',
    mandateType: 'UG',
    assignedTo: 'Laura Hoffmann',
    dateAdded: '2026-06-05',
    status: 'normal',
    notes: 'Mandatsvertrag per DocuSign gesendet. Warten auf Unterschrift.',
    phaseId: 'engagement-letter-sent',
  },
  {
    id: '6',
    clientName: 'Bäckerei Sonnenschein',
    email: 'info@baeckerei-sonnenschein.de',
    phone: '+49 221 6667788',
    mandateType: 'Jahresabschluss',
    assignedTo: 'Thomas Weber',
    dateAdded: '2026-05-20',
    status: 'normal',
    notes: 'Vollständig ongeboardet. Übergabe an Team Buchhaltung erfolgt.',
    phaseId: 'signed-active',
  },
  {
    id: '7',
    clientName: 'Peter Altmann',
    email: 'p.altmann@web.de',
    phone: '+49 155 2223344',
    mandateType: 'Einkommensteuer',
    assignedTo: 'Sarah Müller',
    dateAdded: '2026-05-28',
    status: 'waiting',
    notes: 'Mandant im Urlaub bis Juli. Follow-up am 07.07 geplant.',
    phaseId: 'on-hold',
  },
  {
    id: '8',
    clientName: 'Consulting Pro GmbH',
    email: 'buchhaltung@consultingpro.de',
    phone: '+49 89 4445566',
    mandateType: 'GmbH',
    assignedTo: 'Markus Fischer',
    dateAdded: '2026-06-18',
    status: 'vip',
    notes: 'Empfehlung von Bestandskunde Weber. Hoher Umsatz, braucht Full-Service.',
    phaseId: 'new-inquiry',
  },
];